### ISSUE TITLE
SequenceTubeMap Manifest Not Found

### ISSUE THREAD

**Issue by asunboi** [MoMI-G/MoMI-G#115]
![image](https://github.com/MoMI-G/MoMI-G/assets/66139370/723b87b8-030f-4de4-b380-8e3cc9d59eaa)

Hi! For some reason the yarn build is failing on your branch of sequenceTubeMap. I am using Yarn 4.0.2 and nodejs-20.9.0, with a tunnel to my LocalHost:3000. I am not sure what the issue is here? If you could give any suggestions it would be greatly appreciated.

**Comment by 6br** [comment]
Hi, is it possible to try classic yarn https://classic.yarnpkg.com/lang/en/docs/install/?

**Comment by asunboi** [comment]
Thank you, I believe this fixed the issue.
