### ISSUE TITLE
Error on HPC

### ISSUE THREAD

**Issue by moldach** [MoMI-G/MoMI-G#25]
I'm going to be working with human data in the next month of so, so I need to get `MoMI-G` set up on a server where I don't have root access:

## Install dependencies

```
cd ~/bin/
wget https://nodejs.org/dist/v12.17.0/node-v12.17.0-linux-x64.tar.xz
tar -xf node-v12.17.0-linux-x64.tar.xz  # then set the path
curl -o- -L https://yarnpkg.com/install.sh | bash
```

Next I try to run the `MoMI-G` demo:

```
$ git clone https://github.com/MoMI-G/MoMI-G
$ cd MoMI-G
$ yarn
$ yarn start


Starting the development server...

ts-loader: Using typescript@3.9.3 and /export/home/moldach/bin/MoMI-G/tsconfig.json
no-use-before-declare is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
Tried to lint /export/home/moldach/bin/MoMI-G/src/widgets/tubemap.js but found no valid, enabled rules for this file type and file path in the resolved configuration.
![OKAY](https://user-images.githubusercontent.com/5749465/83081515-20fba280-a03e-11ea-8fdc-aa667a8a228d.png)


Failed to compile.

/export/home/moldach/bin/MoMI-G/src/widgets/SVList.tsx
(337,11): No overload matches this call.
  Overload 1 of 2, '(props: Readonly<Partial<TableProps<any, any>>>): ReactTable<any>', gave the following error.
    Type '{ defaultSorted: { id: string; desc: true; }[]; ref: (r: ReactTable<any>) => ReactTable<any>; loading: boolean; data: any; columns: ({ Header: () => Element; id: string; width: number; Filter: ({ filter, onChange }: { ...; }) => Element; accessor: (d: any) => Element; columns?: undefined; } | { ...; } | { ...; })[];...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactTable<any>> & Readonly<Partial<TableProps<any, any>>> & Readonly<...>'.
      Property 'filters' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactTable<any>> & Readonly<Partial<TableProps<any, any>>> & Readonly<...>'.
  Overload 2 of 2, '(props: Partial<TableProps<any, any>>, context?: any): ReactTable<any>', gave the following error.
    Type '{ defaultSorted: { id: string; desc: true; }[]; ref: (r: ReactTable<any>) => ReactTable<any>; loading: boolean; data: any; columns: ({ Header: () => Element; id: string; width: number; Filter: ({ filter, onChange }: { ...; }) => Element; accessor: (d: any) => Element; columns?: undefined; } | { ...; } | { ...; })[];...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactTable<any>> & Readonly<Partial<TableProps<any, any>>> & Readonly<...>'.
      Property 'filters' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactTable<any>> & Readonly<Partial<TableProps<any, any>>> & Readonly<...>'.
```

A browser window opens up showing this:

![OKAY](https://user-images.githubusercontent.com/5749465/83081522-248f2980-a03e-11ea-9bbf-de24a6a64d42.png)

**Comment by 6br** [comment]
Thank you for reporting us. I assume this version of typescript is inconsistent with the codebase.  I tried to reproduce the same error but I have not reproduced yet. Could you tell me the detail environment (server OS or something)?

**Comment by 6br** [comment]
I updated the latest master by updating dependency. Is it possible to try it again?

**Comment by moldach** [comment]
Okay I've just pulled the latest master and tried again. This time it works. `yarn start` opens up localhost:3000 from the server.

Unfortunately, it's prohibitively slow. Even trying to scroll down takes 20 seconds or more and the responsiveness for clicking/unclicking just one of the "Show Track" boxes took >45 seconds. With this latency it's unusable.

I've noticed performance issues running IGV from this server and the developers said this is a known issue and they suggested that I should try VNC the other day.

Have others noticed performance issues trying to run this from a server? Does using VNC or another method improve performance for MoMIG?

**Comment by 6br** [comment]
Backend server retrieves subgraph from xg file by `vg chunk` command, but sometimes it shows a performance issue when the graph size grows. MoMI-G backend caches a subgraph once you accessed it. The network performance between momi-g backend and momi-g frontend can be an issue, but that impact would be smaller than backend performance. Currently, we run MoMI-G backend on a 16GB memory machine with a multi-core CPU.

**Comment by 6br** [comment]
X forwarding is prohibitively slow because the X protocol is basically designed for local network so short latency is implicitly assumed. VNC is a protocol that allows higher-latency network so should be better. If I open a browser at a local laptop and forward only TCP connections, the large latency wouldn’t be a problem, I guess.

**Comment by moldach** [comment]
Okay I've just figured out how to use VNC protocol on our remote server - I will give it a try. Thanks.
