### ISSUE TITLE
Errors suspected on momig-custom-backend server

### ISSUE THREAD

**Issue by ozakikokoro** [MoMI-G/MoMI-G#48]
Hi, I normally confirmed demo data (CHM1) on beautiful visual panels, but could not do my custom-data.
Thanks to your instructions, I prepared my vcf file and succeeded in executing vcf2xg script without errors.
Then I put my .xg and .pcf as well as config.yaml (copied from the instruction, and changed vg: "vg" and vg_tmp: "vg" both to "vg/bin/vg", which is a PATH of vg indicated in Dockerfile.backend)  into ~/MoMI-G/static directory.

Then I build momig-custom-backend docker image successfully:
```
docker build -t momig-custom-backend -f Dockerfile.backend .
```
And I ran docker image as follows, but **the docker container automatically exited after a few seconds** when I checked by docker container ls -a.
```
$ docker run --init -p 8081:8081 momig-custom-backend
```
So, thereafter, I (sed- changed target to localhost:8081 and ) yarn, yarn started and it once showed [compiled successfully] as follows;
```
Compiled successfully!                                                                                                                     
 You can now view MoMIG in the browser.                                
	Local:            http://localhost:3000/                              
        On Your Network:  http://xxx.xxx.xxx.xxx:3000/                                                                                        
Note that the development build is not optimized.                    \
To create a production build, use yarn build.
```
 but
when I connected to localhost:3000 with firefox browser, error messages appeared and data was not loaded or visualized into MoMI-G frontend ( I suppose). I suspected that backend is not working (**momig-custom-backend docker container is presumed to be working while I connect to localhost:3000, right ?**).
```
Proxy error: Could not proxy request /api/v2/overview?source=features from localhost:3000 to http://localhost:8081/.                        See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).                                                                                                        [HPM] Error occurred while trying to proxy request /api/v2/overview?source=features from localhost:3000 to http://localhost:8081/ (ECONNREFUSED)
(https://nodejs.org/api/errors.html#errors_common_system_errors)      

Proxy error: Could not proxy request /api/v2/overview?source=chromosomes from localhost:3000 to http://localhost:8081/.    
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).                                                                                                        [HPM] Error occurred while trying to proxy request /api/v2/overview?source=chromosomes from localhost:3000 to http://localhost:8081/ (ECONNREFUSED)
(https://nodejs.org/api/errors.html#errors_common_system_errors)      

Proxy error: Could not proxy request /api/v2/overview?source=metadata from localhost:3000 to http://localhost:8081/.      
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).                                                                                                        [HPM] Error occurred while trying to proxy request /api/v2/overview?source=metadata from localhost:3000 to http://localhost:8081/ (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)      

Proxy error: Could not proxy request /api/v2/graph?raw=true&cache=true&gam=true&steps=3&path=chr12:80851974-80853202 from localhost:3000 to http://localhost:8081/. 
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).                                                                                                       

[HPM] Error occurred while trying to proxy request /api/v2/graph?raw=true&cache=true&gam=true&steps=3&path=chr12:80851974-80853202 from localhost:3000 to http://localhost:8081/ (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

**Comment by 6br** [comment]
Thank you for using MoMI-G.

> momig-custom-backend docker container is presumed to be working while I connect to localhost:3000, right ?

Yes. As you mentioned, MoMI-G frontend raises errors when frontend cannot connect to a backend server. Did you see any error messages when MoMI-G backend automatically exited?

**Comment by ozakikokoro** [comment]
Thank you for your reply.
I did not see any error messages when MoMI-G backend automatically exited.

For positive control, I tested nginx server (docker image) by docker run and I can normally saw [welcome to nginx] page on localhost:80 on firefox browser.

But I ran momigteam/momig-backend as follows:
```
~/MoMI-G$ docker run momigteam/momig-backend ./graph-genome-browser-backend --help                                         
~/MoMI-G$
```
it did not show any options or any error messages, but only exited automatically, too.
(Exited container can be confirmed by docker container ls -a command.)

Maybe something is wrong with momigteam/momig-backend docker image or setting for docker.
Could you give me any suggestions, please ?

**Comment by 6br** [comment]
How about using `docker logs` command?
https://docs.docker.com/engine/reference/commandline/logs/

**Comment by ozakikokoro** [comment]
Thank you for your instruction. I tried, and got the following result (nothing appeared in logs).
```
~/MoMI-G$ docker run momigteam/momig-backend ./graph-genome-browser-backend --help     
~/MoMI-G$ docker container ls -a
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                        PORTS               NAMES                                               
665b15876c53        momigteam/momig-backend   "./graph-genome-brow…"   37 seconds ago      Exited (132) 19 seconds ago                    frosty_lamport                                                 
~/MoMI-G$ docker logs 665b15876c53
~/MoMI-G$
```
For comparison, I did the same thing on nginx image and got logs as follows:
```
~/MoMI-G$ docker run nginx
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
^C
~/MoMI-G$ docker container ls -a
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                       PORTS               NAMES                                                           
2cf2a198f3d2        nginx                     "/docker-entrypoint.…"   19 seconds ago      Exited (0) 11 seconds ago                        hardcore_solomon
665b15876c53        momigteam/momig-backend   "./graph-genome-brow…"   7 minutes ago       Exited (132) 7 minutes ago                       frosty_lamport
~/MoMI-G$ docker logs 2cf2a198f3d2
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
~/MoMI-G$
```

**Comment by 6br** [comment]
In general, error 132 is SIGILL signal, which is CPU generated exception.
Some feature used in building momig-backend on dockerhub seems not supported on your machine. 
I suspect the docker is running on machine that doesn't support avx2.

I'd like to know if the cpu supports given feature looks like this:
`cat /proc/cpuinfo | grep flags | head -1 | grep avx2`

**Comment by ozakikokoro** [comment]
Thank you. I executed the command and nothing appeared. I think that avx2 is not supported, as you say.
Should I build backend myself  from source ? (if possible)
```
$ cat /proc/cpuinfo | grep flags | head -1 | grep avx2
$
```

**Comment by 6br** [comment]
I see. I will rebuild backend to support cpu which doesn't have avx2.

**Comment by 6br** [comment]
https://hub.docker.com/r/momigteam/momig-backend/tags?page=1&ordering=last_updated
The latest is built with `-C target-feature=-avx2` option.

**Comment by ozakikokoro** [comment]
Thank you very much ! ...but I git pulled and tried this new image and ended up with the same result and  the same 'Exited (132)' code when I executed "$ docker run momigteam/momig-backend ./graph-genome-browser-backend --help".
cpu flags are as follows:
```
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr
 sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology
 nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid 
dca sse4_1 sse4_2 popcnt aes lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida
 arat flush_l1d
```
Do you need some more information on CPU ?

**Comment by 6br** [comment]
May I ask you which CPU target is the default in your environment?

```
$ rustc --print target-cpus
Available CPUs for this target:
    native         - Select the CPU of the current host (currently broadwell).
```

In this case, `broadwell` is the default target cpu.

**Comment by ozakikokoro** [comment]
Thank you.
As rust has not been installed, I installed rust and executed the command:
```
$ rustc --print target-cpus
Available CPUs for this target: 
native         - Select the CPU of the current host (currently westmere).
and so on
```

**Comment by 6br** [comment]
https://hub.docker.com/r/momigteam/momig-backend/tags?page=1&ordering=last_updated&name=westmere
Is it possible to try the Docker image of westmere tag?

**Comment by ozakikokoro** [comment]
Uhmm,,,,thank you very much indeed. I tried that image, but the result is again the same Exit(132) error.

**Comment by 6br** [comment]
I built the momig-backend-server for generic cpu. https://hub.docker.com/r/momigteam/momig-backend/tags?page=1&ordering=last_updated&name=westmere Could you try it again?

**Comment by ozakikokoro** [comment]
Thank you very much. However, Itried and got the same result and the Exited(132) code.

**Comment by 6br** [comment]
That's strange... Is it possible to build the rust binary or the docker image from the source?
https://github.com/MoMI-G/MoMI-G_backend

**Comment by ozakikokoro** [comment]
Thank you very much for many special modifications. I tested MoMI-G_backend in my another environment(hardware) and confirmed it works. It seems likely that my first environment specifically has intrinsic problems not compatible with MoMI-G_backend after I discussed with the IT-manager. I stop to try to drive backend in the first environment, but anyway many thanks to Dr. 6br. I will be using MoMI-G in another environment.

**Comment by ozakikokoro** [comment]
Hello again.
Now  I retried with docker build (in Dockerfile rustflags target-feature=-avx, -avx2 etc) and successfully ran --help command:
```
$ docker run momig-custom-backend ./graph-genome-browser-backend --help
```

However, when I proceeded to execute the following command, the program exited(101) and produced the error:
```
$ docker run --init -p 8081:8081 momig-custom-backend
thread 'main' panicked at 'couldn't parse config: Scan(ScanError { mark: Marker { index: 239, line: 4, col: 18 }, info: "while parsing a block mapping, did not find expected key" })', src/main.rs:121:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
$
```
Could you give advices to solve this problem if possible ?

**Comment by 6br** [comment]
This error is raised when `config.yaml` is malformed. Could you check it again?

**Comment by ozakikokoro** [comment]
Thank you again. I fixed the config.yaml a few times and succeeded in starting up momig-custom-backend and therafter frontend.
