### ISSUE TITLE
Demo TubeMap not working on corporate networks

### ISSUE THREAD

**Issue by josiahseaman** [MoMI-G/MoMI-G#7]
On Kew Gardens network, the SequenceTubeMap doesn't show up.  It would be great to show a fully working MoMIG demo when we are talking about what platform to start our vg browser work.

![image](https://user-images.githubusercontent.com/2256148/57519151-905b0300-7312-11e9-8205-aeb7a659b895.png)

In Chrome we're seeing JSON syntax errors, which isn't very informative.  On the network tab these are 404 errors in response to Raven requests.
![image](https://user-images.githubusercontent.com/2256148/57519351-f21b6d00-7312-11e9-90bc-16fb46e3fbcb.png)

In Firefox:
![image](https://user-images.githubusercontent.com/2256148/57519547-766df000-7313-11e9-89e9-abb6ba610340.png)
http://chm1.momig.tokyo/api/v3/graph is a 404.

In Edge:
![image](https://user-images.githubusercontent.com/2256148/57519699-d6649680-7313-11e9-87e5-c98f50968947.png)

**Comment by 6br** [comment]
Thank you for your comment. Now I fixed the issue. The demo works.

**Comment by josiahseaman** [comment]
![image](https://user-images.githubusercontent.com/2256148/57930033-d5e87480-78ac-11e9-8012-57d4e874d029.png)

That is looking much better.  How exciting!  There's some debug info on the console too.
