### ISSUE TITLE
starting front- and back-end inside a script

### ISSUE THREAD

**Issue by olechnwin** [MoMI-G/MoMI-G#85]
Hi @6br ,

I am hoping you can help with this. I am trying to automate running front-end and back-end server inside a script so I can run everything by running a single script every time. 

I created `run_momig.sh` which is the single script that will run front and back end servers:
```
# run_momig.sh
#!/bin/bash
set -x
cd ~/../share/simg/momig-singularity/MoMI-G
momig_backend_img=~/../share/simg/momig-singularity/momig-backend.sif
momig_frontend_img=~/../share/simg/momig-singularity/momig-frontend.sif
vcf_path=~/../share/data/A673_pacbio/HiFi/vcf
script_path=~/../share/simg/momig-singularity/scripts

jid=$(sbatch --time=10:00 \
--output=../momig_backend.out \
--job-name=momig_backend \
--wrap "set -x;singularity run --bind $vcf_path:/vg/static --bind /tmp:/vg/tmp --pwd /vg $momig_backend_img"| cut -f 4 -d' ')

node=$(squeue -j $jid -o "%R" -h)
status=$(squeue -j $jid -o "%t" -h)
while [[ $status != "R"* ]];do
	echo -e "Please wait setting up momig-backend server ....\n"
	sleep 10
	node=$(squeue -j $jid -o "%R" -h)
	status=$(squeue -j $jid -o "%t" -h)
done
# 300=5min
sleep 60

jid=$(sbatch --time=10:00 \
--output=../momig_frontend.out \
--job-name=momig_frontend \
--nodelist=$node \
--wrap "singularity exec --bind $script_path:/scripts $momig_frontend_img bash /scripts/momig_frontend.sbatch"| cut -f 4 -d' ')

```
and this is `momig_frontend.sbatch`:
```
#!/bin/bash
cd /opt/MoMI-G
yarn start
```

Back-end server is running fine. Problem is I got this error every time it tries to run the front-end server:
```
yarn run v1.22.10
$ react-app-rewired start --scripts-version react-scripts-ts
error Could not write file "/opt/MoMI-G/yarn-error.log": "EROFS: read-only file system, open '/opt/MoMI-G/yarn-error.log'"
error An unexpected error occurred: "EROFS: read-only file system, mkdir '/gpfs0'"
```
Inside the `momig_frontend.sif`, I had git cloned `MoMI-G` to `/opt/MoMI-G` and had `yarn` installed.

Any insights on how to fix this error?

I should add that running `singularity` outside of `sbatch` just like this `singularity exec --bind $script_path:/scripts $momig_frontend_img bash /scripts/momig_frontend.sbatch` inside the script works. But I needed it to run inside the sbatch so I can then start the firefox.

Thank you in advance for your help.

**Comment by 6br** [comment]
Singularity image is read-only, so you can't write anything. Please copy MoMI-G frontend folder into a host's writable directory and bind the host's directory to `/opt/MoMI-G`. Another suggestion is to use Docker.

**Comment by olechnwin** [comment]
@6br,

Thank you so much for helping me with this.

I'm confused though. Why I can run the frontend like this:
`singularity exec --bind $script_path:/scripts $momig_frontend_img bash /scripts/momig_frontend.sbatch`

But the following will fail:
`sbatch --wrap "singularity exec --bind $script_path:/scripts $momig_frontend_img bash /scripts/momig_frontend.sbatch"`

Anyway, I tried your suggestion to copy the MoMI-G frontend folder into `~/MoMI-G` (host's writable directory) and bind the host's directory to `/momig`. Change the `momig_frontend.sbatch`:

```
#momig_frontend.sbatch
#!/bin/bash
cd /momig
yarn start
```

I installed `yarn` inside the `$momig_frontend_img`. So, running it like so:
`sbatch --wrap "singularity exec --bind ~/MoMI-G:/momig --bind $script_path:/scripts $momig_frontend_img bash /scripts/momig_frontend.sbatch"`

now generates this error:
```
yarn run v1.22.10
$ react-app-rewired start --scripts-version react-scripts-ts
error An unexpected error occurred: "EROFS: read-only file system, mkdir '/gpfs0'".
info If you think this is a bug, please open a bug report with the information provided in "/momig/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
This time, it was able to create the file `/momig/yarn-error.log` but then tries to `mkdir /gpfs0` which I don't have access to.

Again, in this case the command works if I don't use `sbatch`.

**Comment by 6br** [comment]
It's weird that react-app-rewired runs `mkdir /gpfs0`. Alternatively, MoMI-G frontend can serve with MoMI-G backend without using react-app-rewired.

```bash
$ yarn global add serve
$ yarn build 
```

Then, `./build` directory will be built on the current directory. Here, storing the path for the built directory in $momig_build_path.

When running MoMI-G backend, the built frontend can be served at the same time with the following command.

```bash
$ singularity run --bind $vcf_path:/vg/static --bind $momig_build_path:/vg/build --bind /tmp:/vg/tmp --pwd /vg $momig_backend_img /vg/graph-genome-browser-backend --config=/vg/static/config.yaml --interval=1500000 --http=0.0.0.0:8081 --api=/api/v2/ --tmp=/tmp/ --serve
```

**Comment by olechnwin** [comment]
Thanks for your suggestion. I've tried following your instruction above, and browse to 0.0.0.0:8081 instead of localhost:3000
It's showing an empty page:
![image](https://user-images.githubusercontent.com/20069067/123673461-7dfff400-d80e-11eb-95b2-6ba494c525aa.png)

and these are the messages:
```
[2021-06-28T16:37:18Z INFO  graph_genome_browser_backend::vg] VG Version: vg version v1.25.0 "Apice"
Compiled with g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 on Linux
Linked against libstd++ 20191114
Built by root@7032b439058e

[2021-06-28T16:37:18Z INFO  graph_genome_browser_backend::vg] VG minor version: 25
[2021-06-28T16:37:18Z INFO  graph_genome_browser_backend::features] Parsing:  "static/gencode.v37lift37.basic.annotation.gff3"
[2021-06-28T16:37:59Z DEBUG graph_genome_browser_backend::features] 1844760 lines processed. end.
25
Start server on 0.0.0.0:8081
[2021-06-28T16:38:51Z INFO  logger] GET http://0.0.0.0:8081/ 200 OK (1.318558 ms)
[2021-06-28T16:38:51Z INFO  logger] GET http://0.0.0.0:8081/demo2/static/css/main.0c9c7af8.css 404 Not Found (0.046607 ms)
[2021-06-28T16:38:51Z ERROR iron::iron] Error handling:
Request {
    url: Url { generic_url: "http://0.0.0.0:8081/demo2/static/css/main.0c9c7af8.css" }
    method: Get
    remote_addr: V4(127.0.0.1:56904)
    local_addr: V4(0.0.0.0:8081)
}
Error was: Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-06-28T16:38:51Z INFO  logger] GET http://0.0.0.0:8081/demo2/static/js/main.8e6aab43.js 404 Not Found (0.016962 ms)
[2021-06-28T16:38:51Z ERROR iron::iron] Error handling:
Request {
    url: Url { generic_url: "http://0.0.0.0:8081/demo2/static/js/main.8e6aab43.js" }
    method: Get
    remote_addr: V4(127.0.0.1:56906)
    local_addr: V4(0.0.0.0:8081)
}
Error was: Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-06-28T16:38:51Z INFO  logger] GET http://0.0.0.0:8081/demo2/static/js/main.8e6aab43.js 404 Not Found (0.026399 ms)
[2021-06-28T16:38:51Z ERROR iron::iron] Error handling:
Request {
    url: Url { generic_url: "http://0.0.0.0:8081/demo2/static/js/main.8e6aab43.js" }
    method: Get
    remote_addr: V4(127.0.0.1:56906)
    local_addr: V4(0.0.0.0:8081)
}
Error was: Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-06-28T16:38:51Z INFO  logger] GET http://0.0.0.0:8081/favicon.ico 200 OK (0.970236 ms)
```

**Comment by 6br** [comment]
Is it possible to run `yarn build` on the latest master of MoMI-G?

**Comment by olechnwin** [comment]
> Is it possible to run `yarn build` on the latest master of MoMI-G?

Sorry. I'm not sure what you meant. So, I have yarn installed on my singularity image `$momig_frontend_img`. In the above steps, I run '`yarn build`' on the host on the directory where I had git cloned MoMI-G. Are you asking me to run '`yarn build`' on my singularity image `$momig_frontend_img` ? what is latest?

**Comment by 6br** [comment]
Sorry for my lack of explanation. The error above is due to MoMI-G frontend's unexpected request for the backend. Because I updated MoMi-G repository to avoid the error above, MoMI-G needs to be built on the latest master of the GitHub repository. Thus, is it possible to perform `git pull` on the host's directory where you had git cloned MoMi-G and retry `yarn build` again? If there is still the same error, please let me know.

**Comment by olechnwin** [comment]
@6br, sorry I haven't had time to try this until today. 
Thank you so much for your kind clarification. I'm super happy to report that this works!!
I really appreciate your help. Many Thanks!

**Comment by 6br** [comment]
I'm happy to hear that!
